//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Architectural overview and usage guide: 
// http://blogofrab.blogspot.com/2010/08/maintenance-free-mocking-for-unit.html
//------------------------------------------------------------------------------
using System.Data.EntityClient;
using System.Data.Objects;
using ActivityMonitor.ReportingEntitiesMockObjectSet;

namespace ActivityMonitor
{
    /// <summary>
    /// The concrete mock context object that implements the context's interface.
    /// Provide an instance of this mock context class to client logic when testing, 
    /// instead of providing a functional context object.
    /// </summary>
    public partial class ReportingEntitiesMock : IReportingEntities
    {
        public IObjectSet<tbDailyActivityGP> tbDailyActivityGP
        {
            get { return _tbDailyActivityGP  ?? (_tbDailyActivityGP = new MockObjectSet<tbDailyActivityGP>()); }
        }
        private IObjectSet<tbDailyActivityGP> _tbDailyActivityGP;
        public IObjectSet<tbHealthBoardContacts> tbHealthBoardContacts
        {
            get { return _tbHealthBoardContacts  ?? (_tbHealthBoardContacts = new MockObjectSet<tbHealthBoardContacts>()); }
        }
        private IObjectSet<tbHealthBoardContacts> _tbHealthBoardContacts;
        public IObjectSet<tbInactiveSites> tbInactiveSites
        {
            get { return _tbInactiveSites  ?? (_tbInactiveSites = new MockObjectSet<tbInactiveSites>()); }
        }
        private IObjectSet<tbInactiveSites> _tbInactiveSites;
        public IObjectSet<tbMsg> tbMsg
        {
            get { return _tbMsg  ?? (_tbMsg = new MockObjectSet<tbMsg>()); }
        }
        private IObjectSet<tbMsg> _tbMsg;
        public IObjectSet<tbOrganisation> tbOrganisation
        {
            get { return _tbOrganisation  ?? (_tbOrganisation = new MockObjectSet<tbOrganisation>()); }
        }
        private IObjectSet<tbOrganisation> _tbOrganisation;
        public IObjectSet<tbOrgSupplier> tbOrgSupplier
        {
            get { return _tbOrgSupplier  ?? (_tbOrgSupplier = new MockObjectSet<tbOrgSupplier>()); }
        }
        private IObjectSet<tbOrgSupplier> _tbOrgSupplier;
        public IObjectSet<tbSupplierContacts> tbSupplierContacts
        {
            get { return _tbSupplierContacts  ?? (_tbSupplierContacts = new MockObjectSet<tbSupplierContacts>()); }
        }
        private IObjectSet<tbSupplierContacts> _tbSupplierContacts;

        // Implemented the following methods myself

        public int SaveChanges() { return 0; }   
        public void DeleteObject(object entity)
        {
            // Only called from tbInactiveSites but need to make this more generic....
            tbInactiveSites _organisation = (tbInactiveSites)entity;

            this.tbInactiveSites.DeleteObject(_organisation);
        }  
    }
}
