//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ActivityMonitor
{
    public partial class tbMigratingSites
    {
        #region Primitive Properties
    
        public virtual string Organisation
        {
            get;
            set;
        }
    
        public virtual string FutureSupplier
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> PlannedMigrationDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateNotificationEmailSent
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DateUpdated
        {
            get;
            set;
        }
    
        public virtual string OriginalSupplier
        {
            get;
            set;
        }

        #endregion
    }
}
