//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ActivityMonitor
{
    public partial class tbRPT_PRSErrorMonitor
    {
        #region Primitive Properties
    
        public virtual System.DateTime DateTime
        {
            get;
            set;
        }
    
        public virtual int PRSUnavailableErrors
        {
            get;
            set;
        }
    
        public virtual int PRSTimeoutErrors
        {
            get;
            set;
        }

        #endregion
    }
}
