//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ActivityMonitor
{
    public partial class tbRPT_DailyActivityGP
    {
        #region Primitive Properties
    
        public virtual string org
        {
            get;
            set;
        }
    
        public virtual System.DateTime date
        {
            get;
            set;
        }
    
        public virtual Nullable<short> amsPrescriptions
        {
            get;
            set;
        }
    
        public virtual Nullable<short> amsCancellations
        {
            get;
            set;
        }
    
        public virtual Nullable<short> amsAmendments
        {
            get;
            set;
        }
    
        public virtual Nullable<short> cmsPrescriptions
        {
            get;
            set;
        }
    
        public virtual Nullable<short> cmsCancellations
        {
            get;
            set;
        }
    
        public virtual Nullable<short> cmsUpdatesRequests
        {
            get;
            set;
        }
    
        public virtual Nullable<short> cmsTreatmentUpdates
        {
            get;
            set;
        }
    
        public virtual Nullable<short> cmsComplianceUpdates
        {
            get;
            set;
        }
    
        public virtual Nullable<short> gpRegistrationUpdatesRequests
        {
            get;
            set;
        }

        #endregion
    }
}
